[features]
seeds = false
[programs.devnet]
mint_nft = "BJKfnpMh2ebHQ7txvVWWpFvVJq75U8NXEMMaTEtftz1u"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Volumes/CodeSpace/blockchain/solana/solana-learning/wallets/id.json"

[scripts]
test-mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-mint.ts"
test-sell = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-sell.ts"